name: Trigger day run & schedule benchmarks
on:
  workflow_dispatch:
    inputs:
      day:
        description: "Day to run benchmarks for"
        required: true

permissions:
  contents: write
  actions: write

jobs:
  get-repos:
    runs-on: ubuntu-24.04
    outputs:
      repositories: ${{ steps.data.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: data
        run: echo "matrix=$(jq -c . < ./data/repositories.json)" >> $GITHUB_OUTPUT

  schedule:
    runs-on: ubuntu-24.04
    needs: get-repos
    strategy:
      fail-fast: false
      matrix:
        repository: ${{fromJson(needs.get-repos.outputs.repositories)}}

    steps:
      - name: Print metadata
        run: |
          echo "Owner: ${{ matrix.repository.owner }}"
          echo "Name: ${{ matrix.repository.name }}"
          echo "Crate: ${{ matrix.repository.crate }}"
          echo "Toolchain: ${{ matrix.repository.toolchain }}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare the runner
        working-directory: ./rust-runner
        run: |
          REPO_URL="https://github.com/${{ matrix.repository.owner }}/${{ matrix.repository.name }}"
          if [ -n "${{ matrix.repository.crate }}" ]; then
            cargo add --git $REPO_URL ${{ matrix.repository.crate }} --rename solution
          else
            cargo add --git $REPO_URL --rename solution
          fi
          echo "[toolchain]" > ../rust-toolchain.toml
          echo "channel = \"${{ matrix.repository.toolchain }}\"" >> ../rust-toolchain.toml

      - name: Prepare the branch & schedule the run
        run: |
          git config --global user.name "codspeed-advent[bot]"
          git config --global user.email "codspeed-advent-bot@@users.noreply.github.com"
          git add rust-runner/* rust-toolchain.toml
          BRANCH_NAME="run/${{ matrix.repository.owner }}/${{ matrix.repository.name }}/${{ inputs.day }}"
          git checkout -b $BRANCH_NAME
          git commit -m "Run: $BRANCH_NAME"
          git push --force origin $BRANCH_NAME
          gh workflow run run-day.yml --ref $BRANCH_NAME --repo ${{ github.repository }}
          RUN_ID=$(gh run list --limit 1 --branch $BRANCH_NAME --json databaseId | jq '.[0].databaseId')
          echo "Scheduled the run for $BRANCH_NAME"
          echo "::notice::Measurement Job URL: https://github.com/CodSpeedHQ/Advent/actions/runs/$RUN_ID"
        env:
          GH_TOKEN: ${{ github.token }}
